### ISSUE TITLE
Error accumulation

### ISSUE THREAD

**Issue by Gloix** [jhermsmeier/node-google-polyline#2]
Given a list of coordinates with more than 5 decimals the coordinates start to drift ever so slightly during the encode function, resulting in errors that show most notably at small scale and with long lists.

Example:

    decode(encode([[0.000003,0],[0.000008,0],[0.000013,0],[0.000029,0],[0.000045,0],[0.000061,0],[0.000077,0],[0.000093,0]]))

expected result:

    [[0,0],[0.00001,0],[0.00001,0],[0.00003,0],[0.00005,0],[0.00006,0],[0.00008,0],[0.00009,0]]

actual result:

    [[0,0],[0,0],[0,0],[0.00002,0],[0.00004,0],[0.00006,0],[0.00008,0],[0.0001,0]]

I found that the culprit is during the difference computation, which doesn't take into account the desired result after rounding. I could fix the encoding function by replacing lines 8 and 9 with

    str += encode.chars( encode.sign( (Math.round(values[i]*1e5) - Math.round(px*1e5))/1e5 ) )
    str += encode.chars( encode.sign( (Math.round(values[i + 1]*1e5) - Math.round(py*1e5))/1e5 ) )

Although the fix would add some overhead and is not optimized, I'll leave the decision up to the maintainer to further optimize the above code or simply drop it to preserve performance.

**Comment by jhermsmeier** [comment]
Hey @Gloix, thanks for this! I'd be happy to accept a PR changing it. Regarding performance, I think improved correctness is of more value than speed.

**Comment by Gloix** [comment]
Nice! Submitted PR #3 to fix the issue along with a test for it.
