### ISSUE TITLE
Crash when `value` is undefined or null

### ISSUE THREAD

**Issue by dkoprowski** [jhermsmeier/node-google-polyline#7]
https://github.com/jhermsmeier/node-google-polyline/blob/ae65bdaf9b2e6e5ba6c13ca4d2b8c6e0b7beaf4a/lib/decode.js#L33

This could be secured somehow because user can pass `undefined`, null or other value to the `decode` function and it causes app crash.

For example `decode(null)` or `decode(undefined)` causes crashes in React Native apps.

Simply use type check before loop execution would be enough I guess

**Comment by jhermsmeier** [comment]
That is expected behaviour. If calling a function or method in your application with invalid input crashes it, then that's not in the scope of this module. 

Use a type/null check before calling `decode()`, and default to whatever suits the situation.
